### ISSUE TITLE
Refactoring generation script

### ISSUE THREAD

**Issue by Julien-R44** [Shinigami92/eslint-define-config#134]
I think it would be cool to do a good refactoring of the type generation script ( `scripts/generate-rule-file.ts` ). 
Currently, for a newcomer to the codebase ( like me 😋 ), it's quite complicated to understand/maintain or extend. And this is the core of eslint-define-config.

If you're interested I can try to propose a PR with something cleaner ( from my POV ), when I have some time to do it. And by the way, adding some tests would be awesome. 

Since you are very active in the Vite ecosystem, I imagine that you would be more in favor of using Vitest. 
However, I would still like to suggest to use [Japa](https://japa.dev), a test runner that I help to maintain and make evolve. It is a test runner that is focused on testing NodeJS libs/applications, and that does not perform any code transformation.

However, if you prefer Vitest, no worries, it is also a tool that I absolutely love. 💖

Feel free to close the issue if you are not interested, no worries !

**Comment by Shinigami92** [comment]
> Feel free to close the issue if you are not interested, no worries !

Lol 😂... my thought was more like: if you do all the PRs and Issues in a good way, I'm willing to sponsor you 1-2 cups of Coffee ☕️ / ~10€ 💸

But yes, please use Vitest. I use it in all my projects since Vitest was created.

Feel also free to split the generate file into more smaller pieces and maybe generate also settings and such out from a plugin.
Also maybe we can clean the JSDocs somehow automatically.

**Comment by Julien-R44** [comment]
Haha okay, cool, thanks a lot man. I just didn't want to be too intrusive 😋

**Comment by Shinigami92** [comment]
I also think about to provide a param to the script so only one given plugin will get generated / updated instead of all at once
