### ISSUE TITLE
Generating `node/file-extension-in-import` results in a type error

### ISSUE THREAD

**Issue by Shinigami92** [Shinigami92/eslint-define-config#141]
<img width="600" alt="image" src="https://user-images.githubusercontent.com/7195563/193869839-ebeaa5be-4346-410b-9006-0cb50de25e84.png">

**Comment by Julien-R44** [comment]
Okay so this error is caused by https://github.com/bcherny/json-schema-to-typescript generating this invalid type.

The old version you show in the diff was a manual modification

So I guess I don't feel like going to fork json-schema-to-typescript to fix this bug, I think it would be a bit complicated. ( I'll probably look at it in more detail ).

What is on the other hand can be done quite easily, is to implement a patch on our side : 
We could just make a small method that analyzes the AST of each rule file. If ever it detects this pattern, then it will automatically correct it by replacing it with an union

**Comment by Shinigami92** [comment]
@Julien-R44 I already exactly thought about the second proposed strategy: implementing a rule-patcher system where you can register some rules with a patched that will be applied on generating.

**Comment by Julien-R44** [comment]
Ahah, perfect, I'll do that then 😋

**Comment by Shinigami92** [comment]
> Ahah, perfect, I'll do that then yum

@Julien-R44 And because I love your reporter and terminal colors :green_heart: how about showing e.g. in a yellow-ish color how many were patched while generating :slightly_smiling_face:

**Comment by Dimava** [comment]
This problem also happens in updated `@graphql-eslint/naming-convention`

I have encountered this problem while doing #177 and chose to just write a replacer
```ts

      // fix generated object type having incompatible index signature
      // and narrow it down to starts-with-dot as per documentation
      case 'node/file-extension-in-import': {
        this.content = this.content.replace(
          `
        tryExtensions?: string[];
        [k: string]: 'always' | 'never';`,
          `
        tryExtensions?: string[];
        [ext: \`.\${string}\`]: 'always' | 'never';`,
        );
        break;
      }
```
