### ISSUE TITLE
Predefined string configurations in flat config seem to be deprecated

### ISSUE THREAD

**Issue by DamianGlowala** [Shinigami92/eslint-define-config#226]
When using:
```
export default ['eslint:recommended']
```
... I receive:

> The 'eslint:recommended' string configuration is deprecated and will be replaced by the @eslint/js package's 'recommended' config.

Shall the following type be removed?
https://github.com/Shinigami92/eslint-define-config/blob/2eac0b22b1c7f22487a32dc7ccf6476a73fb7765/src/flat-config/index.d.ts#L73

**Comment by Shinigami92** [comment]
First time hearing about https://www.npmjs.com/package/@eslint/js at all ^^
Not sure if we need backwards compatibility for older eslint versions there 🤔 
I think right now it is mostly used with LiteralUnion, is it? So it's just a suggestion.
Is it a hard break since a specific version of FlatConfig? I'm not used to FlatConfig until today at all.

/ping @sxzz

**Comment by DamianGlowala** [comment]
I think I found the relevant commit and issue:

https://github.com/eslint/eslint/commit/c8c0c715a2964cc1859b99f9d4f542675094d1d5
https://github.com/eslint/eslint/issues/16537

I would certainly remove it only from the flat config types :)

**Comment by sxzz** [comment]
> (node:75845) Warning: The 'eslint:recommended' string configuration is deprecated and will be replaced by the @eslint/js package's 'recommended' config.

Predefined string configurations are not removed by ESLint official but deprecated. Maybe we can mark it deprecated in jsdoc, and remove them after ESLint did this.
